#!/bin/bash

rm -rf build_production

rm -rf dist

echo "Building Blog ..."

cd _www

rm -rf build_production

npm run production

vendor/bin/jigsaw build production

cd ..

mv _www/build_production build_production

minify -s -r -o dist/ build_production

rm -rf dist/build

cp -rf build_production/assets dist/
