#!/bin/bash

rm -rf build_production

echo "Building Blog ..."

cd _www

rm -rf build_production

npm run production

vendor/bin/jigsaw build production

find source/assets/img/ -name "*.jpg" -exec jpegoptim -m80 -o -p --strip-all {} \;

cd ..

mv _www/build_production build_production
